const MOVIES_CONST = {
  REQUEST_MOVIES: 'REQUEST_MOVIES',
  REQUEST_CURRENT_MOVIE: 'REQUEST_CURRENT_MOVIE',

  SET_MOVIES: 'SET_MOVIES',
  SET_CURRENT_MOVIE: 'SET_CURRENT_MOVIES'
};

export default MOVIES_CONST;